export const cars = 
[
    {
        id : '1',
        name : 'Nissan GTR',
        model : 'GT-R (R-35)',
        year  : 2011,
        doors  : 2,
        ac    : 'AC/Heater',
        transmission : 'Automatic',
        fuel : 'Petrol',
        image : './img/nissan.png',
        price : 381,
    },
    {
        id : '2',
        name : 'Audi',
        model : 'R8',
        year : 2018,
        doors : 2,
        ac  : 'AC/Heater',
        transmission : 'Dual clutch S-Tronic',
        fuel : 'Gasoline',
        image : './img/audi.png',
        price : 234,
    },
    {
        id : '3',
        name : 'Toyota',
        model : 'Toyota Auris',
        year : 2013,
        doors : 2,
        ac  : 'AC/Heater',
        transmission : 'Automatic',
        fuel : 'Gasoline',
        image : "./img/toyota.png",
        price : 214,
    },
    {
        id : '4',
        name : 'Honda',
        model : 'Honda Civic',
        year : 2018,
        doors : 2,
        ac : 'AC/Heater',
        transmission : 'Automatic',
        fuel : 'Gasoline',
        image : './img/honda.png',
        price : 391

    },
    {
        id : '5',
        name : 'Chevrolet',
        model : 'Chevrolet Camaro',
        year : 2024,
        doors : 2,
        ac : 'AC/Heater',
        transmission : 'Automatic',
        fuel : ' 91-Cctane',
        image : './img/Chevrolet.png',
        price : 421,
    },
    {
        id : '6',
        name : 'Lamborghini',
        model : 'Lamborghini Aventador',
        year : 2013,
        doors : 2,
        ac : 'AC/Heater',
        transmission : 'Automated manual gearbox',
        fuel : 'Gasoline',
        image : './img/lambo.png',
        price : 312,
    },
    {
        id : '7',
        name : 'BMW',
        model : 'BMW i8',
        year : 2020,
        doors : 2,
        ac : 'AC/Heater',
        transmission : 'Transverse Automatic',
        fuel : 'Gasoline',
        image : './img/bwmcar.png',
        price : 219,
    }
]